services:
  web:
    container_name: espace-image:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=${TZ:-America/Montreal}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
