"""baseline: initial schema from models

Revision ID: 120becb0bbf1
Revises: None
Create Date: 2026-05-04 12:46:40.871678

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "120becb0bbf1"
down_revision: str | Sequence[str] | None = "f09dc931e3e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
