"""baseline: initial schema from models

Revision ID: f09dc931e3e2
Revises: None
Create Date: 2026-05-04 12:46:35.030101

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f09dc931e3e2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
