"""baseline_schema

Revision ID: f823da104bcb
Revises:
Create Date: 2026-05-01 10:48:40.550095

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f823da104bcb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
